### ISSUE TITLE
Support for Intel Simulator

### ISSUE THREAD

**Issue by manasv** [oliverepper/pjproject-apple-platforms#1]
Hey, first of all, really neat project / script, I work for a client that use other script to generate a framework but I think yours is far better and easily integrated into a Swift Package.

I've tried to generate a slice for intel iOS simulator and then grouping in a fat framework (and worked), after running the changed I was able to generate it, but the mac slice wasn't inside the output xcframework, so I don't know if I messed up something haha.

Will try implement this myself and see if I can put a PR for it, or if it's implemented by someone that has more experience with this kind of scripts it will be fine.

Actually is not as important. I also work on an m1 mac but we have some coworkers or even CI that runs on Intel.

Thanks in advance for your job, giving some love to pjsip on apple plattforms ❤️

**Comment by oliverepper** [comment]
Tell me if you need any assistance.

**Comment by manasv** [comment]
Solved in #2 

Closed.
